default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: code_test_development
  username: ttam
  password: guest

test:
  <<: *default
  database: code_test_test
  username: ttam
  password: guest


staging:
  adapter:  sqlite3
  database: db/staging_database.sqlite3

production:
  adapter:  mysql2
  database: code_test_production
  encoding: utf8
  pool:     5
  host:     <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
